# Copyright (C) 2022 TomTom NV. All rights reserved.
#
# This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
# used for internal evaluation purposes or commercial use strictly subject to separate
# license agreement between you and TomTom NV. If you are the licensee, you are only permitted
# to use this software in accordance with the terms of your license agreement. If you are
# not the licensee, you are not authorized to use this software in any manner and should
# immediately return or destroy it.

name: SonarQube scan
author: Raptor team
description: SonarQube scan

inputs:
  url:
    description: URL of the SonarQube instance
    required: false
    default: https://sonar.tomtomgroup.com

  token:
    description: Token for authentication with Sonar
    required: true

  config:
    description: Sonar Project configuration file
    required: false
    default: "sonar-project.properties"

  version:
    description: Version of the project
    required: false

  build-wrapper:
    description: Build command to run as part of the Sonar Build Wrapper
    required: false

outputs:
  cli:
    description: Path towards the installed Sonar Scanner CLI tool

  build-wrapper:
    description: Path towards the installed Build Wrapper CLI tool

  project-name:
    description: Project name read from sonar-project.properties

runs:
  using: 'node16'
  main: 'index.js'
